
projection TestProjection;
component MOVIE;
layer Core;
description "Put some useful description here ...";
//category Users;

statemachine MrsGrantsSecretCompartment

event doorClosed
event drawOpened
event lightOn
event panelClosed

projection TestProjection;
component MOVIE;
layer Core;
description "Put some useful description here ...";
//category Users;
category Users;

----------------------------- MAIN ENTRY POINTS -----------------------------
entityset Movies for Movie;


------------------------------ ENTITY DETAILS -------------------------------